services:
  backend:
    build:
      context: ./server/
      dockerfile: Dockerfile.backend
    container_name: backend
    volumes:
      - ./server/:/app
    ports:
      - "7999:7999"
    env_file:
      - ./server/.env
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_DB: fastapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./front/LookData/
      dockerfile: Dockerfile.frontend
    container_name: vue-frontend
    expose:
      - "80"
    depends_on:
      - backend
    ports:
      - "213:80"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data:
